Codebase/simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

Codebase/simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

Codebase/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('basic_app/',include('basic_app.urls',namespace='basic_app')),
    path('register/',include('tour.urls',namespace='tour')),
]

Codebase/simplesocial/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    path('',views.StudentsListView.as_view(),name='list'),
    path('<int:pk>/',views.StudentsDetailView.as_view(),name='detail'),
    path('create/',views.StudentsCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.StudentsUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.StudentsDeleteView.as_view(),name='delete')
]

Codebase/simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Tour</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
    <link rel="stylesheet" href="{% static 'simplesocial/css/fontback.css'%}">

  </head>
  <body class='loader'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">
            <img height="50" width="50" src="{% static 'img/travel_logo.png' %}" alt="logo">
        </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="navbar-nav ml-auto collapse navbar-collapse flex-grow-0" id="navbarsExampleDefault">
          {% if user.is_authenticated and request.user.is_superuser %}
            <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'tour:list' %}" class="btn btn-simple">Registered</a>
            <a class="nav-item nav-link" href="{% url 'tour:create' %}" class="btn btn-simple">Register</a>
            <a class="nav-item nav-link" href="{% url 'basic_app:list' %}" class="btn btn-simple">Info</a>
            <a class="nav-item nav-link" href="{% url 'basic_app:create' %}" class="btn btn-simple">Add Info</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% elif user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'tour:list' %}" class="btn btn-simple">Registered</a>
            <a class="nav-item nav-link" href="{% url 'tour:create' %}" class="btn btn-simple">Register</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'tour:list' %}" class="btn btn-simple">Registered</a>
            <a class="nav-item nav-link" href="{% url 'tour:create' %}" class="btn btn-simple">Register</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <p></p>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

Codebase/simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1 class="text">Welcome To CSE 25 Tour Site</h1>
    <h4 class="text">You can register at the top to let others know about your journey</h4>
    <h5 class="text"><em>Free signup to create group,post and share your idea's</em></h5>

{% endblock %}

Codebase/simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container text">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>

</div>

{% endblock %}

Codebase/simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1 class="text">Lets have a greate tour together!!</h1>

{% endblock %}