Codebase/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('basic_app/',include('basic_app.urls',namespace='basic_app')),
    path('register/',include('tour.urls',namespace='tour')),
]

Codebase/simplesocial/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    path('',views.StudentsListView.as_view(),name='list'),
    path('<int:pk>/',views.StudentsDetailView.as_view(),name='detail'),
    path('create/',views.StudentsCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.StudentsUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.StudentsDeleteView.as_view(),name='delete')
]

Codebase/simplesocial/tour/models.py
from django.db import models
from django.urls import reverse

class Students(models.Model):
    name = models.CharField(max_length=256)
    batch = models.IntegerField()
    roll  = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("tour:detail",kwargs={'pk':self.pk})

Codebase/simplesocial/tour/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models

class SuperuserRequiredMixin(object):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(SuperuserRequiredMixin, self).dispatch(*args, **kwargs)

class IndexView(SuperuserRequiredMixin,TemplateView):

    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection!"
        return context

class StudentsListView(ListView):

    model = models.Students

class StudentsDetailView(SuperuserRequiredMixin,DetailView):
    context_object_name = 'students_details'
    model = models.Students
    template_name = 'tour/students_detail.html'


class StudentsCreateView(CreateView):
    fields = ("name","roll","batch")
    model = models.Students
    success_url = reverse_lazy("tour:list")


class StudentsUpdateView(SuperuserRequiredMixin,UpdateView):
    fields = ("name","roll","batch")
    model = models.Students
    success_url = reverse_lazy("tour:list")

class StudentsDeleteView(SuperuserRequiredMixin,DeleteView):
    model = models.Students
    success_url = reverse_lazy("tour:list")

Codebase/simplesocial/tour/templates/tour/students_confirm_delete.html
{% extends "tour/tour_base.html" %}

{% block body_block %}
<h1>Delete {{students.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'tour:list' %} ">Cancel</a>

</form>

{% endblock %}

Codebase/simplesocial/tour/templates/tour/students_detail.html
{% extends "tour/tour_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the Registered student's Detail Page</h1>
    <h2>Student Details:</h2>
    <p>Name: {{register_details.name}}</p>
    <p>Roll: {{register_details.roll}}</p>
    <p>Batch: {{register_details.batch}}</p>


  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'tour:update' pk=register_details.pk %}">Update</a>
      <a class='btn btn-danger' href="{% url 'tour:delete' pk=register_details.pk %}">Delete</a>
    </p>
  </div>

{% endblock %}

Codebase/simplesocial/tour/templates/tour/students_form.html
{% extends "tour/tour_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Registration for tour
  {% else %}
  Update tour registration
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

Codebase/simplesocial/tour/templates/tour/students_list.html
{% extends "tour/tour_base.html" %}
{% block body_block %}
  <div>

    <h1>Welcome to the List of Students Page!</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Roll</th>
          <th scope="col">Batch</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for info in students_list %}
        <tr>
          <td>{{ info.name }}</td>
          <td>{{ info.roll }}</td>
          <td>{{ info.batch }}</td>
          <td><a class='btn btn-warning' href="{% url 'tour:update' pk=info.pk %}"><i class="fa fa-wrench" aria-hidden="true"></i></a>
          <a class='btn btn-danger' href="{% url 'tour:delete' pk=info.pk %}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


{% endblock %}

Codebase/simplesocial/tour/templates/tour/tour_base.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	{% block body_block %}
	{% endblock %}

	</div>
{% endblock %}